use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let devices_dir = Path::new("vendor/mirajazz-json/devices");

    if !devices_dir.exists() {
        panic!(
            "Device directory not found: {}. Did you initialize git submodules? Run: git submodule update --init",
            devices_dir.display()
        );
    }

    // Collect all .json files
    let mut entries = Vec::new();
    for entry in fs::read_dir(devices_dir).expect("Failed to read devices directory") {
        let entry = entry.expect("Failed to read directory entry");
        let path = entry.path();

        if path.extension().and_then(|e| e.to_str()) == Some("json") {
            let filename = path
                .file_name()
                .and_then(|n| n.to_str())
                .expect("Invalid filename");
            let content = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("Failed to read {}: {}", path.display(), e));

            // Escape the content for string literal
            let escaped_content = content
                .replace('\\', "\\\\")
                .replace('"', "\\\"")
                .replace('\n', "\\n")
                .replace('\r', "\\r")
                .replace('\t', "\\t");

            entries.push((filename.to_string(), escaped_content));
        }
    }

    // Sort by filename for consistent ordering
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    // Generate the Rust source file
    let mut source = String::from(
        "// Auto-generated by build.rs - DO NOT EDIT\n\
         // Device JSON files embedded from vendor/mirajazz-json/devices/\n\n\
         pub const EMBEDDED_DEVICES: &[(&str, &str)] = &[\n",
    );

    for (filename, content) in &entries {
        source.push_str(&format!("    (\"{}\", \"{}\"),\n", filename, content));
    }

    source.push_str("];\n");

    // Write to OUT_DIR
    let dest_path = Path::new(&out_dir).join("embedded_devices.rs");
    fs::write(&dest_path, source).expect("Failed to write embedded_devices.rs");

    println!("cargo:rerun-if-changed=vendor/mirajazz-json/devices");
    println!(
        "cargo:warning=Embedded {} device definition(s) into binary",
        entries.len()
    );
}
